name: CI
on:
  push:
  workflow_dispatch:

jobs:
  tests:
    name: Test ${{ matrix.os }} ${{ matrix.rust }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        rust: [nightly, beta, stable, 1.56.0]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
            toolchain: ${{matrix.rust}}
            components: rust-src
      - run: cargo test --all-features

  doc:
    name: Documentation
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: -Dwarnings
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - uses: dtolnay/install@cargo-docs-rs
      - run: cargo docs-rs

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, rust-src
      - run: cargo clippy --tests -- -Dclippy::all -Dclippy::pedantic
